---
- hosts: almalinux8
  name: Test connectivité AAP
  tasks:
    - ansible.builtin.debug:
        msg:
          - "Ansible Distribution : {{ ansible_distribution }}"
          - "Ansible Dist version : {{ ansible_distribution_version }}"
