---
- hosts: almalinux
  name: Test connectivité AAP
  tasks:
    - name: "Récupération des services existants"
      service_facts:
    - name: "HTTPD ou NGINX running"
      ansible.builtin.debug:
        msg: "Services running"
      when: '"nginx.service' in services or 'httpd.service' in services" 
