---
- hosts: almalinux
  name: Test connectivité AAP
  tasks:
    - ansible.builtin.debug:
        msg:
          - "Ansible Distribution : {{ ansible_distribution }}"
          - "Ansible Dist version : {{ ansible_distribution_version }}"
    - name: Set env variables test
      ansible.builtin.set_fact:
        test=test2
    - name: Afficher variable
      ansible.builtin.debug:
        msg: "Env: {{ test }}"
